application: prototype-149014
version: 17
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /
  static_files: site/dist/index.html
  upload: site/dist/index.html

- url: /
  static_dir: site/dist