application: prototype-149014
version: 17
runtime: go
api_version: go1

handlers:
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: site/dist/\1
  upload: site/dist/(.*\.js)

- url: /(.*\.css)
  static_files: site/dist/\1
  upload: site/dist/(.*\.css)

- url: /(.*)
  static_files: site/dist/index.html
  upload: site/dist/index\.html

- url: /api/.*
  script: _go_app